# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Keyword-test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'AlamofireImage', '~> 3.5'

  # Pods for Keyword-test

  target 'Keyword-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Keyword-testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
